### ISSUE TITLE
Webhook url?

### ISSUE THREAD

**Issue by Igetin** [sooyhwang/Simple-Echo-Telegram-Bot#2]
Readme.md includes this sentence: "Please exchange the TOKEN, the webhook URL, and the HOOK path with your own."

I understand the token part, but what am I supposed to put in the URL or HOOK? Can someone help me?

**Comment by sooyhwang** [comment]
URL is your server address (your Flask root), and HOOK is some random secret string. [Telegram recommends using your Token for the hook](https://core.telegram.org/bots/api#setwebhook) because it is random and not known to outside world, but it's just one example.

Hope this helps!

**Comment by Igetin** [comment]
Thank you for the info!

**Comment by Igetin** [comment]
A small request: could you send me a working example of the bot_gae.py? With URL, HOOK and TOKEN configured. It would be easier for me to compare that to my own file, because I don't quite understand what's wrong with it.

**Comment by sooyhwang** [comment]
Sorry, but no. Those are sensitive private information and I wouldn't disclose them. If you need help, join the Telegram chat group at https://github.com/leandrotoledo/python-telegram-bot#contact and ask for help.

**Comment by Igetin** [comment]
I've already joined it. :)
